apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: name
          image: nginx:1.6.1
          ports:
            - containerPort: 80
